  server {
      ### Don't Touch This
      listen <LISTEN_PORT>;
      server_name localhost;
      root <WEBROOT>;
      ###

      ### Populate your custom directives here
      index  index.html index.htm;

      location / {
        client_max_body_size 50M;
        try_files $uri $uri/index.html $uri.html @puma;
      }

      location /assets {
        add_header Cache-Control max-age=3600;
      }

      location @puma {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:5000;
      }

      ### Don't edit past here
      include /etc/nginx/nginx.conf.d/site_optimization.conf;
      include /etc/nginx/nginx.conf.d/exploit_protection.conf;
}
